title: nexxel's snippets
description: These are a collection of code snippets I've used in the past and saved.
rootName: index
description: I am writing about my experiences as a naval navel-gazer
url: "https://snippets.nexxel.dev/"
author:
  name: Shoubhit Dash
  email: shoubhit2005@gmail.com
  url: "https://nexxel.dev"
